spring:
  application:
    name: Defect-management

  datasource:
    url: jdbc:mysql://root:WZneEzJMyQkkAfZJzbWoIMUkzizWyfIp@autorack.proxy.rlwy.net:36054/railway
    username: root
    password: WZneEzJMyQkkAfZJzbWoIMUkzizWyfIp
    driver-class-name: com.mysql.cj.jdbc.Driver

  
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false